<a href="https://colab.research.google.com/github/HariomPrajapati09/Machine-Learning/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Pandas Library***

Useful for Data Processing & Analysis


***Pandas Data Frame:***

Pandas DataFrame is two-dimensional tabular data structure with labeled axes (rows & columns).

In [ ]:
import pandas as pd

Importing the data from a CSV file to a Pandas DataFrame

In [ ]:
dia_df=pd.read_csv('/content/diabetes.csv')
type(dia_df)

pandas.core.frame.DataFrame

In [ ]:
dia_df.head()

# 1-represent true
# 0- represent false

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
dia_df.shape

(768, 9)

**Loading the data from a excel file to a pandas dataframe:**

**pd.read_excel('file.path')**

**Exporting a DataFrame to a csv and excel file**

**df.to_csv('filename.csv')**

**df.to_excel('filename.excel')**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
randon_df=pd.DataFrame(np.random.rand(20,10))

In [ ]:
randon_df.head()

,0,1,2,3,4,5,6,7,8,9
0,0.877422,0.794778,0.417662,0.454295,0.249658,0.605974,0.743804,0.427868,0.112584,0.652729
1,0.971280,0.818870,0.144777,0.543719,0.223095,0.814386,0.300745,0.101390,0.196403,0.623453
2,0.320279,0.362675,0.759952,0.396298,0.738858,0.246215,0.844179,0.978742,0.360250,0.564592
3,0.067405,0.304337,0.729324,0.338663,0.223395,0.293746,0.558620,0.309348,0.712878,0.304548
4,0.335367,0.841539,0.725901,0.076474,0.803132,0.035718,0.344278,0.073653,0.218832,0.922886

In [ ]:
randon_df.shape

(20, 10)

In [ ]:
#For last 5 datas
randon_df.tail()

,0,1,2,3,4,5,6,7,8,9
15,0.399943,0.685920,0.163005,0.997842,0.400352,0.633123,0.419514,0.786824,0.163316,0.500760
16,0.723105,0.505257,0.122005,0.258630,0.563372,0.042046,0.631904,0.111913,0.496384,0.839386
17,0.226549,0.466531,0.242135,0.358453,0.190671,0.222745,0.019152,0.263526,0.493050,0.353455
18,0.403421,0.686931,0.818142,0.504176,0.772136,0.355435,0.745500,0.855662,0.484867,0.185493
19,0.344079,0.996171,0.715932,0.757962,0.904602,0.706832,0.273657,0.062872,0.668197,0.118751

In [ ]:
randon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     float64
 1   1       20 non-null     float64
 2   2       20 non-null     float64
 3   3       20 non-null     float64
 4   4       20 non-null     float64
 5   5       20 non-null     float64
 6   6       20 non-null     float64
 7   7       20 non-null     float64
 8   8       20 non-null     float64
 9   9       20 non-null     float64
dtypes: float64(10)
memory usage: 1.7 KB

In [ ]:
#finding the number of missing values
randon_df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [ ]:
#counting the value based on labels
randon_df.value_counts(5)

5
0.035718    1
0.042046    1
0.814386    1
0.706832    1
0.644824    1
0.633123    1
0.623086    1
0.605974    1
0.488320    1
0.444957    1
0.364269    1
0.355435    1
0.293746    1
0.264553    1
0.246215    1
0.222745    1
0.126295    1
0.100150    1
0.050634    1
0.835849    1
Name: count, dtype: int64

In [ ]:
#group the values based on the mean
randon_df.head().groupby(5).mean()

,0,1,2,3,4,6,7,8,9
5,,,,,,,,,
0.035718,0.335367,0.841539,0.725901,0.076474,0.803132,0.344278,0.073653,0.218832,0.922886
0.246215,0.320279,0.362675,0.759952,0.396298,0.738858,0.844179,0.978742,0.360250,0.564592
0.293746,0.067405,0.304337,0.729324,0.338663,0.223395,0.558620,0.309348,0.712878,0.304548
0.605974,0.877422,0.794778,0.417662,0.454295,0.249658,0.743804,0.427868,0.112584,0.652729
0.814386,0.971280,0.818870,0.144777,0.543719,0.223095,0.300745,0.101390,0.196403,0.623453

**Stattistical Measures**

In [ ]:
#count the number of values
randon_df.count()

0    20
1    20
2    20
3    20
4    20
5    20
6    20
7    20
8    20
9    20
dtype: int64

In [ ]:
#mean values column wise
randon_df.mean()

0    0.449716
1    0.561408
2    0.423788
3    0.511011
4    0.563604
5    0.394958
6    0.476748
7    0.371323
8    0.534041
9    0.504165
dtype: float64

In [ ]:
#Standard deviation - column wise
randon_df.std()

0    0.265598
1    0.286229
2    0.285148
3    0.251106
4    0.276361
5    0.262307
6    0.308459
7    0.308450
8    0.256916
9    0.288872
dtype: float64

In [ ]:
#minimum value in each column
randon_df.min()

0    0.067405
1    0.008263
2    0.019424
3    0.064012
4    0.010306
5    0.035718
6    0.019152
7    0.035987
8    0.112584
9    0.118751
dtype: float64

In [ ]:
#maximum value in each column
randon_df.max()

0    0.971280
1    0.996171
2    0.988844
3    0.997842
4    0.904602
5    0.835849
6    0.992199
7    0.978742
8    0.972197
9    0.922886
dtype: float64

In [ ]:
#all the statistical measures about the dataframe
randon_df.describe()

,0,1,2,3,4,5,6,7,8,9
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,0.449716,0.561408,0.423788,0.511011,0.563604,0.394958,0.476748,0.371323,0.534041,0.504165
std,0.265598,0.286229,0.285148,0.251106,0.276361,0.262307,0.308459,0.308450,0.256916,0.288872
min,0.067405,0.008263,0.019424,0.064012,0.010306,0.035718,0.019152,0.035987,0.112584,0.118751
25%,0.301895,0.422408,0.177774,0.376026,0.339291,0.198633,0.269294,0.096536,0.349429,0.224533
50%,0.366378,0.564204,0.400854,0.498269,0.629641,0.359852,0.400796,0.311621,0.549182,0.532676
75%,0.533202,0.800801,0.718424,0.626336,0.779885,0.625596,0.744228,0.554544,0.689473,0.725582
max,0.971280,0.996171,0.988844,0.997842,0.904602,0.835849,0.992199,0.978742,0.972197,0.922886

***Manipulatinf dataframes***

**1. Adding a column to a dataframe:-**

**dataframe['columnName']=dataset.target**

**2. Removing a particular row:-**

**dataframe.drop(index=indexvalue,axis=0)**

**3. Removing a particular column:-**

**dataframe.drop(columns='columnName',axis=1)**

**4. Locationg a row using the index valur:-**

**dataframe.iloc[index]**

**5. Locationg a particular column using the index valur:-**

**dataframe.iloc[ : ,index]**

***Correlation:***
1. **Positive correlation**
2. **Negative correlation**

For check correlation:

**dataframe.corr()**

1. Positive correlation:- if one value will increase another will also increase.
2. Negative correlation:- if one value will increase another will decrease.